#!/usr/bin/env bash
# Builds site/ into build/site/ with a generated config.js, uploads that, and
# invalidates CloudFront.
#
# The committed site/config.js stays on its placeholder values: the copy that
# carries the real ones is written into build/, which is gitignored, so a
# deploy never leaves deployment values in the working tree.
#
# Usage: scripts/deploy_site.sh
set -euo pipefail
cd "$(dirname "$0")/.."

PYTHON="${PYTHON:-python}"

if [ ! -f .env ]; then
  echo "ERROR: No .env -- copy env.example to .env and fill it in." >&2
  exit 1
fi

set -a
source .env
set +a

for name in S3_BUCKET AWS_REGION AWS_PROFILE; do
  if [ -z "${!name:-}" ]; then
    echo "ERROR: $name is not set in .env -- see env.example." >&2
    exit 1
  fi
done

DOMAIN=$("$PYTHON" scripts/tf.py output -raw site_domain)
DISTRIBUTION_ID=$("$PYTHON" scripts/tf.py output -raw cloudfront_distribution_id)

rm -rf build/site
mkdir -p build/site
# The local preview artefacts and the folder's own README are not deployed.
tar -cf - --exclude=manifest.json --exclude=sample-photos --exclude=README.md -C site . | tar -xf - -C build/site

cat > build/site/config.js << EOF
// GENERATED by scripts/deploy_site.sh into build/ -- not the committed copy.
export const MANIFEST_URL = "/data/manifest.json";
export const API_BASE = "/api";
export const SITE_TITLE = "${SITE_TITLE:-Mementos}";
EOF

aws s3 sync build/site/ "s3://${S3_BUCKET}/site/" \
  --profile "${AWS_PROFILE}" --region "${AWS_REGION}" --delete

aws cloudfront create-invalidation \
  --distribution-id "${DISTRIBUTION_ID}" --paths "/*" \
  --profile "${AWS_PROFILE}"

echo "Deployed to https://${DOMAIN}/"
